"""update reviews table

Revision ID: 5815c88f5e00
Revises: 94a1107c304d
Create Date: 2025-08-29 12:27:16.665136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5815c88f5e00'
down_revision = '94a1107c304d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('individual_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_individual_id_individuals'), 'individuals', ['individual_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_individual_id_individuals'), type_='foreignkey')
        batch_op.drop_column('individual_id')

    # ### end Alembic commands ###
