"""add a fave cinema table

Revision ID: 853755b559ac
Revises: 1abd0964dabe
Create Date: 2025-08-28 18:42:56.738362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853755b559ac'
down_revision = '1abd0964dabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fave_cinemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], name=op.f('fk_fave_cinemas_cinema_id_cinemas')),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], name=op.f('fk_fave_cinemas_individual_id_individuals')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fave_cinemas')
    # ### end Alembic commands ###
