"""initial migration

Revision ID: 94a1107c304d
Revises: 
Create Date: 2025-08-29 12:17:24.767303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a1107c304d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_title', sa.String(), nullable=True),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('film_api_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('ac_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cinemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address_1', sa.String(), nullable=False),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('town', sa.String(), nullable=True),
    sa.Column('post_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_cinemas_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('fk_individuals_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('fave_cinemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('individual_id', sa.Integer(), nullable=True),
    sa.Column('cinema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], name=op.f('fk_fave_cinemas_cinema_id_cinemas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['individual_id'], ['individuals.id'], name=op.f('fk_fave_cinemas_individual_id_individuals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fave_cinemas')
    op.drop_table('individuals')
    op.drop_table('cinemas')
    op.drop_table('users')
    op.drop_table('reviews')
    # ### end Alembic commands ###
