"""add showings list with endpoint defined

Revision ID: a32b7b4dde7f
Revises: 5815c88f5e00
Create Date: 2025-08-31 08:47:40.708602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32b7b4dde7f'
down_revision = '5815c88f5e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_showings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('screen', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.Column('film_api_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], name=op.f('fk_cinema_showings_cinema_id_cinemas')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema_showings')
    # ### end Alembic commands ###
