"""update individual and cinema tables

Revision ID: eecab55bc9dd
Revises: 853755b559ac
Create Date: 2025-08-28 18:59:30.780928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eecab55bc9dd'
down_revision = '853755b559ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fave_cinemas', schema=None) as batch_op:
        batch_op.alter_column('individual_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cinema_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fave_cinemas', schema=None) as batch_op:
        batch_op.alter_column('cinema_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('individual_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
